### ISSUE TITLE
KeyError: 'title'

### ISSUE THREAD

**Issue by fraun** [iCHAIT/moviemon#5] opened 2016-02-25 15:02 UTC
Traceback (most recent call last):  
  File "/usr/local/bin/moviemon", line 9, in <module>
    load_entry_point('moviemon==1.0.11', 'console_scripts', 'moviemon')() 
  File "/usr/local/lib/python2.7/dist-packages/moviemon/moviemon.py", line 61, in main 
    util(args)  
  File "/usr/local/lib/python2.7/dist-packages/moviemon/moviemon.py", line 77, in util 
    scan_dir(docopt_args["PATH"], dir_json)  
  File "/usr/local/lib/python2.7/dist-packages/moviemon/moviemon.py", line 281, in scan_dir 
    data = get_movie_info(name)  
  File "/usr/local/lib/python2.7/dist-packages/moviemon/moviemon.py", line 302, in get_movie_info 
    return omdb(movie_info['title'], None)  
KeyError: 'title'

**Comment by iCHAIT** [comment] 2016-03-30 17:40
@fraun  Extremely sorry for not replying earlier and thanks for reporting. Other users have also faced this same issue, I am closing this issue as it is duplicate of of #3, please read my comment on that issue, do note that I have not fixed this issue yet.

**Closed as completed by iCHAIT** 2016-03-30 17:40 UTC
